<?xml version="1.0"?>
<package format="3">
  <name>imu_pkg</name>
  <version>0.1.0</version>
  <description>Estimacion de actitud, velocidad y posicion con el MPU-6050 (micro-ROS).</description>
  <maintainer email="alumno@example.com">Grupo IMU</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
